// <auto-generated />
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Form.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210716054841_prodinit")]
    partial class prodinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Domain.Dossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ConsentOne")
                        .HasColumnType("bit");

                    b.Property<bool>("ConsentTwo")
                        .HasColumnType("bit");

                    b.Property<string>("CsOneQuestionFive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsOneQuestionFour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsOneQuestionOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsOneQuestionSix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsOneQuestionThree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsOneQuestionTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsTwoQuestionFive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsTwoQuestionFour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsTwoQuestionOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsTwoQuestionSix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsTwoQuestionThree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsTwoQuestionTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organisation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dossiers");
                });
#pragma warning restore 612, 618
        }
    }
}
